### ISSUE TITLE
Setup difficulty

### ISSUE THREAD

**Issue by ng4biba** [ColumbiaJS/hw1#2]
Hello,
I am having difficulty to setup and install some of the applications. Almost all setups and applications are unfamiliar to me but I managed to get a github account and install node.js and npm. Somehow I get an error when trying to install grunt and bower. here is a capture to describe my problem.
![screen shot 2015-01-27 at 2 10 15 am](https://cloud.githubusercontent.com/assets/2974577/5914793/c51f4008-a5c9-11e4-903e-f687be007a58.png)

**Comment by morrishopkins** [comment]
Your installation of node requires administrative privileges in order to install packages. Rerun the same command with sudo (super user do)  prepended.  e.g. sudo npm install -g bower
