### ISSUE TITLE
"Illegal trailing whitespace" error when running Gulp tests

### ISSUE THREAD

**Issue by ohEmily** [ColumbiaJS/hw1#4]
Hi,

Several parts of my code are annoying gulp with trailing whitespace. Why is this so bad?

I'm under the impression that gulp may be checking for style errors, because it also called me out for having an if statement without curly braces, but I'm not sure.

EDIT: Found it! Line 8 of gulpfile.js includes ['gulp-jscs'](https://www.npmjs.com/package/gulp-jscs), which enforces a style guide.

**Comment by levbrie** [comment]
Exactly! And I do recommend that you try to stick to this style guide as your learning - it will prevent a lot of mistakes and also make it much easier when you start working in teams/developing larger applications.  The style guide expects that you indent tabs using spaces and that you indent 2 spaces for tabs.  You can easily set this specifically for JavaScript in any editor.  If you're having trouble getting this to work you can comment out that line of the gulpfile for this lesson, changing lines 20 and 21 from:

``` js
               .pipe(jshint.reporter('jshint-stylish'))
               .pipe(jscs({configPath: '.jscsrc'}));
```

to:

``` js
               .pipe(jshint.reporter('jshint-stylish'));
               // .pipe(jscs({configPath: '.jscsrc'}));
```
