### ISSUE TITLE
incorrect last spec on ballfollower.spec.js

### ISSUE THREAD

**Issue by minsoo91** [ColumbiaJS/hw1#5]
in line 42 of ballfollower.spec.js
Given var swaps = [[0, 9], [9, 3], ...], and start = 0, it asserts new BallFollower(0, swaps).swap() to equal(2). In reality, it should equal(9)

**Comment by levbrie** [comment]
@minsoo91 Given a start value of 0 and the swaps on line 41, the result of calling swap on line 42 should indeed be 2, not 9.  Is it possible that you've misunderstood something about the way that swapping works, or that I was unclear in some part of the README?  If so, and why it should be 2 still seems unclear, please comment on this and reopen the issue.
