### ISSUE TITLE
'for each' statement error

### ISSUE THREAD

**Issue by ng4biba** [ColumbiaJS/hw1#6]
I have this message error when trying to use 'for each' statement:

  'for each' is only available in Mozilla JavaScript extensions (use moz option).

  ⚠  1 warning

**Comment by levbrie** [comment]
@ng4biba Most likely this means that you have written code with `for each` in it when you should actually be using the JavaScript `Array.prototype.forEach()` method.  `for each` is deprecated and should not be used.  Try to make sure to look these terms up on MDN when I refer to them so you don't get confused, as they do mean very different things:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for_each...in

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
